### ISSUE TITLE
No compiler message when calling an abstract method that needs to be defined

### ISSUE THREAD

**Issue by lmove** [alien-tools/maracas#33]
The Maven and JDT compiler do not report a compilation error when calling an abstract method that needs to be defined within the class. Do we want Maracas to report such cases?

Related broken use:
```
Path: path-to/maracas/test-data/comp-changes/client/src/mainclient/methodNowAbstract/MethodNowAbstractExt.java
Line: 17
Breaking change: METHOD_NOW_ABSTRACT
API use: METHOD_INVOCATION
Used declaration: methodNowAbstract()
Source declaration: methodNowAbstract()

Path: path-to/maracas/test-data/comp-changes/client/src/mainclient/methodNowAbstract/MethodNowAbstractExt2.java
Line: 17
Breaking change: METHOD_NOW_ABSTRACT
API use: METHOD_INVOCATION
Used declaration: methodNowAbstract()
Source declaration: methodNowAbstract()
```

**Comment by tdegueul** [comment]
If neither Maven nor JDT complains, it seems that we shouldn't either. But my understanding is that it's actually a broken use because it's possible to instantiate `T` if it's a concrete class  and then  invoke a method that wouldn't have an implementation. Maybe this is allowed so that someone can instantiate an anonymous subclass of `T` that would provide an implementation and that's the only valid use? I don't know, I'm not sure :grimacing:

**Comment by tdegueul** [comment]
Okay, I get it now---thanks for the explanation! We can report a broken use in such a case, I agree; let's keep it this way.
