### ISSUE TITLE
No broken use when overriding removed method 

### ISSUE THREAD

**Issue by lmove** [alien-tools/maracas#47]
Maracas does not report a broken use when overriding a removed method.

Related compiler messages:
```
Path: path-to/maracas/test-data/comp-changes/client/src/mainclient/methodRemoved/MethodRemovedExt.java
Line: 15
Message: method does not override or implement a method from a supertype
```

**Comment by tdegueul** [comment]
I recently patched the code that handles this case: https://github.com/alien-tools/maracas/commit/05b50372373b5dc7e312b297b9dd112f83e89c21.

The reason was that `isOverriding` is _extremely_ expensive, and due to the way our visitors work, `isOverriding` would be invoked on virtually every singe method in the client. Maybe I introduced this bug as a side effect and the `isOverriding` version was working?

**Comment by lmove** [comment]
This issue was related to #32. Closing issue.
