### ISSUE TITLE
The same broken use is reported multiple times

### ISSUE THREAD

**Issue by KarinaMankevic** [alien-tools/maracas#71]
By running analysis on several libraries, I have noticed a case where Maracas reported 3 broken uses for **the same breaking change** and **on the same line**. 

In particular, I detected this case by running Maracas on the following client an library combination:
- api1: ca.uhn.hapi.fhir:hapi-fhir-base:1.3
- api2: ca.uhn.hapi.fhir:hapi-fhir-base:1.4
- c1: org.openehealth.ipf.platform-camel:ipf-platform-camel-ihe-fhir:3.1-20160122
- c2: org.openehealth.ipf.platform-camel:ipf-platform-camel-ihe-fhir:3.1-20160314

Below I list 3 different reported broken uses that belong to the same breaking change that affected the client (on the same line!):

______________________________________
[ANNOTATION_DEPRECATED_ADDED]
	Element: client = context.newRestfulGenericClient(path) (FhirProducer.java:53)
	Used:    ca.uhn.fhir.rest.client.IGenericClient
	Source:  ca.uhn.fhir.rest.client.IGenericClient
	Use:     TYPE_DEPENDENCY
______________________________________
[ANNOTATION_DEPRECATED_ADDED]
	Element: context.newRestfulGenericClient(path) (FhirProducer.java:53)
	Used:    ca.uhn.fhir.rest.client.IGenericClient
	Source:  ca.uhn.fhir.rest.client.IGenericClient
	Use:     TYPE_DEPENDENCY
______________________________________
[ANNOTATION_DEPRECATED_ADDED]
	Element: client (FhirProducer.java:53)
	Used:    ca.uhn.fhir.rest.client.IGenericClient
	Source:  ca.uhn.fhir.rest.client.IGenericClient
	Use:     TYPE_DEPENDENCY

By looking at the example above, I believe this is a bug. Is this on Maracas side or perhaps the underlying tools (e.g.Spoon)? Is this something that can be fixed?

**Comment by lmove** [comment]
Dear @KarinaMankevic ,

Thanks for sharing your issue with us. This issue is related to #25. If you look carefully at the **element** value, you will see that it differs in the three cases:

- Case 1: `client = context.newRestfulGenericClient(path) (FhirProducer.java:53)`
- Case 2: `context.newRestfulGenericClient(path) (FhirProducer.java:53)`
- Case 3: `client (FhirProducer.java:53)`

Maracas is pointing to *different code elements* located in the *same file + line*. Although, at first sight, this looks like a duplicate it is not the case. Please, let us know if you need any further assistance.

**Comment by KarinaMankevic** [comment]
Thank you for the explanation @lmove !
